login: &login
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password:

connection: &connection
  encoding: unicode
  pool: 5

development:
  database: cfpt_dev
  <<: *login
  <<: *connection

test:
  database: cfpt_tests
  <<: *login
  <<: *connection

production:
  database: cfpt
  <<: *login
  <<: *connection
