method: :smtp
settings:
  :address: smtp.gmail.com
  :port: 587
  :domain: fruga.pt
  :enable_starttls_auto: true
  :authentication:  :plain
  :user_name: <%= ENV['CFSMTP'] %>
  :password: <%= ENV['CFSMTP_PASSWORD'] %>
